language: go
go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
install:
  - go get github.com/stretchr/testify
  - go get github.com/mattn/goveralls
  - go get github.com/blang/semver
script:
  - go test -covermode=count -coverprofile=coverage.out -v github.com/ronelliott/go-opts
after_success:
  - goveralls -service travis-ci -covermode=count -coverprofile=coverage.out -repotoken=$COVERALLS_REPO_TOKEN
